import { createClient } from '@supabase/supabase-js'
import * as dotenv from 'dotenv'
dotenv.config({ path: '.env.local' })

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
)

const posts = [
  { month: 'April 2026', date_label: 'Apr 25', title: 'ANZAC Day', format: 'photo', status: 'pending', provider: 'Moses', asset_needed: 'Ceremony photo', caption: 'Wreaths and hymns marked ANZAC Day in Adamstown Square — remembrance across the Pacific. #ANZACDay #LestWeForget' },
  { month: 'May 2026', date_label: 'May 2', title: 'World Tuna Day', format: 'photo', status: 'needs_content', asset_needed: 'Reef photo', caption: 'Migratory tuna pass through Pitcairn waters, now protected in the MPA. #TunaDay #MarineConservation' },
  { month: 'May 2026', date_label: 'May 10', title: 'Migratory Bird Day', format: 'photo', status: 'needs_content', asset_needed: 'Bird colony photo', caption: "DID YOU KNOW: Ducie Island hosts 95% of the world's Murphy's petrels — seabirds on global journeys. #BirdDay #PitcairnWildlife" },
  { month: 'May 2026', date_label: 'May (TBD)', title: 'Honey Fact 3', format: 'photo', status: 'needs_content', asset_needed: 'Honey jars photo', caption: "Honey so sweet, even the Queen of England praised its award-winning pure honey! #PitcairnHoney #GreatTasteAwards" },
  { month: 'May 2026', date_label: 'May (TBD)', title: 'Market Day', format: 'video', status: 'needs_content', asset_needed: 'Phone clip — on island', caption: 'A clip from the Square showed crafts, produce, and neighbors trading together. #PitcairnCommunity #IslandLife' },
  { month: 'May 2026', date_label: 'May (TBD)', title: '10 Year Blue Belt / Community Center', format: 'photo', status: 'needs_content', asset_needed: 'TBD', caption: null },
  { month: 'June 2026', date_label: 'Jun 5', title: 'World Environment Day', format: 'photo', status: 'needs_content', asset_needed: 'Valley photo', caption: 'Pitcairners celebrate Environment Day today and everyday with our invasive plant control and seabird monitoring. #EnvironmentDay #IslandNature' },
  { month: 'June 2026', date_label: 'Jun 8', title: 'World Ocean Day', format: 'photo', status: 'needs_content', asset_needed: 'Ocean photo', caption: 'Happy World Ocean Day from Pitcairn! #WorldOceanDay #BlueBelt #PitcairnMPA' },
  { month: 'June 2026', date_label: 'Jun (TBD)', title: '10 Year Blue Belt Anniversary', format: 'photo', status: 'needs_content', asset_needed: 'TBD — needs planning', caption: null },
  { month: 'June 2026', date_label: 'Jun 25', title: 'Day of the Seafarer', format: 'photo', status: 'needs_content', asset_needed: 'Longboat photo', caption: "Generations lived by the sea — from the Bounty longboats to today's Silver Supporter. #SeafarerDay #PitcairnHeritage" },
  { month: 'June 2026', date_label: 'Jun (TBD)', title: 'Cliff Waves', format: 'video', status: 'needs_content', asset_needed: 'Phone clip — on island', caption: "A clip of waves breaking on volcanic cliffs — the Pacific's power ever present. #PitcairnNature #IslandLife" },
  { month: 'July 2026', date_label: 'Jul 2', title: 'Pitcairn Day', format: 'photo', status: 'needs_content', asset_needed: 'Feast photo — on island', caption: 'Pitcairn Day brought the community together with food, music, and celebration. #PitcairnDay #IslandCelebration' },
  { month: 'July 2026', date_label: 'Jul 16', title: 'Marathon', format: 'photo', status: 'needs_content', asset_needed: 'Runners photo — on island', caption: "Runners tackled Pitcairn's steep course — ocean views on every ridge. #PitcairnMarathon #AdventureRunning" },
  { month: 'July 2026', date_label: 'Jul 28', title: 'World Conservation Day', format: 'photo', status: 'needs_content', asset_needed: 'Wildlife photo', caption: "Partnerships help keep Pitcairn's biodiversity thriving. #ConservationDay #PitcairnNature" },
  { month: 'July 2026', date_label: 'Jul (TBD)', title: 'Feast', format: 'video', status: 'needs_content', asset_needed: 'Phone clip — on island', caption: 'Islanders shared food and song under the Norfolk pines — community spirit alive. #PitcairnCommunity #IslandLife' },
  { month: 'August 2026', date_label: 'Aug 1', title: 'MPA Day', format: 'photo', status: 'needs_content', asset_needed: 'Aerial photo', caption: "Pitcairn's 842,000 km² sanctuary protects whales, sharks, tuna, and seabirds. #MPADay #MarineConservation" },
  { month: 'August 2026', date_label: 'Aug (TBD)', title: 'Whale Shark Day', format: 'photo', status: 'needs_content', asset_needed: 'Ocean photo', caption: 'Whale sharks — rare but unforgettable — highlight life in Pitcairn waters. #WhaleSharks #PitcairnMPA' },
  { month: 'August 2026', date_label: 'Aug (TBD)', title: 'Honey Fact 4', format: 'photo', status: 'needs_content', asset_needed: 'Honey jars photo', caption: 'Pitcairn honey is certified disease-free — approved for export by New Zealand MPI. #PitcairnHoney #PureAndNatural' },
  { month: 'August 2026', date_label: 'Aug 18', title: 'Cruise Ship', format: 'video', status: 'needs_content', asset_needed: 'Phone clip — on island', caption: 'Cruise ship anchored off Pitcairn — longboats shuttling passengers ashore. #PitcairnCruises #AdventureTravel' },
  { month: 'September 2026', date_label: 'Sep (TBD)', title: 'Blue Belt Expedition / Science', format: 'photo', status: 'needs_content', asset_needed: 'Science team photo', caption: 'Scientists and locals worked together to study biodiversity across the Pitcairn MPA. #MarineScience #BlueBelt' },
  { month: 'September 2026', date_label: 'Sep 25', title: 'World Maritime Day', format: 'photo', status: 'needs_content', asset_needed: 'Longboats photo', caption: "Maritime Day reflected Pitcairn's story at sea — from the Bounty to Silver Supporter. #MaritimeDay #IslandHeritage" },
  { month: 'September 2026', date_label: 'Sep 27', title: 'World Tourism Day', format: 'photo', status: 'needs_content', asset_needed: 'Tourist market photo', caption: 'Pitcairn is one of the rarest destinations to reach, but worth the voyage. #TourismDay #RemoteTravel' },
  { month: 'September 2026', date_label: 'Sep (TBD)', title: 'Expedition Clip', format: 'video', status: 'needs_content', asset_needed: 'Phone clip — on island', caption: "Islanders and scientists shared discoveries walking Pitcairn's shorelines. #PitcairnCommunity #MarineScience" },
  { month: 'Evergreen', date_label: 'Any time', title: 'Miro Wood', format: 'photo', status: 'pending', provider: 'Rachael', asset_needed: 'Miro wood / forest photo', caption: "One of Pitcairn's best-known natural resources is miro wood, a beautiful hardwood used by local artisans to create many of the island's signature hand-carved pieces.\n\nHarvested carefully and in small amounts, often from naturally fallen trees or selective cutting, miro supports a craft tradition that stays closely tied to the island's environment.\n\nFrom serving platters and turtles to dolphins, birds, key rings, magnets and the iconic Bounty model, these carvings reflect Pitcairn's long history of craftsmanship.\n\nPitcairn's miro carving heritage has even been featured on a Pitcairn postage stamp.\n\nCurious to see handcrafted miro pieces? Visit https://pitkernartisangallery.pn/search?q=miro" },
  { month: 'Evergreen', date_label: 'Any time', title: 'Historic Weather Station', format: 'photo', status: 'pending', provider: 'Rachael', asset_needed: 'Weather station interior photo', caption: "Living on one of the world's most remote islands means keeping a close eye on the weather.\n\nWe recognise the role weather observations have long played on Pitcairn Islands, where sea and land conditions shape daily life. From landing longboats to planning fishing trips and supply ship arrivals, weather has always mattered.\n\nShown here inside Pitcairn's historic weather station are instruments once used to record pressure, sunshine, wind, rainfall and temperature. These readings created a daily record and connected this small island to the wider world of meteorology.\n\nWeather remains central to island life, and upgrades are underway this year to improve monitoring systems and future forecasting." },
  { month: 'Evergreen', date_label: 'Any time', title: 'Honey Fact 2', format: 'photo', status: 'needs_content', asset_needed: 'Honey jars photo', caption: "DID YOU KNOW: The rich taste of Pitcairn honey comes from blooms like mango, guava, passion flower, rose apple, and lata. #PitcairnHoney #PitcairnFlora" },
  { month: 'Evergreen', date_label: 'Any time', title: 'Ocean Swells / Bounty Bay', format: 'photo', status: 'needs_content', asset_needed: 'Phone clip — on island', caption: 'Swells rolled into Bounty Bay, longboats pulled onto the slip — island life tied to the sea. #PitcairnHeritage #IslandLife' },
  { month: 'Evergreen', date_label: 'Any time', title: 'Oeno Island', format: 'photo', status: 'needs_content', asset_needed: 'Lagoon photo', caption: 'Oeno Island lagoon — pristine and uninhabited, a summer retreat for Pitcairners. #OenoIsland #HiddenParadise' },
  { month: 'Evergreen', date_label: 'Any time', title: "Mutineers' Graveyard", format: 'video', status: 'needs_content', asset_needed: 'Phone clip — on island', caption: "A quiet walk through the Mutineers' Graveyard — final resting place of Bounty descendants. #PitcairnHistory #BountyLegacy" },
  { month: 'Evergreen', date_label: 'Any time', title: 'Forest Walk / Eco Trail', format: 'video', status: 'needs_content', provider: 'Moses', asset_needed: 'Phone clip — on island', caption: "The peaceful Eco Trail — shaded trees and birdsong in Pitcairn's valleys. #EcoTrail #PitcairnNature" },
  { month: 'Evergreen', date_label: 'Any time', title: 'New Longboat', format: 'photo', status: 'needs_content', asset_needed: 'Launch photo — on island', caption: 'A new longboat joined the fleet — seaworthy and ready for landings and supply runs. #PitcairnHeritage #IslandLife' },
]

async function seed() {
  const { error } = await supabase.from('posts').insert(posts)
  if (error) { console.error(error); process.exit(1) }
  console.log(`Seeded ${posts.length} posts successfully.`)
}

seed()
